; Listing generated by Microsoft (R) Optimizing Compiler Version 19.15.26726.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Windows\TEMP\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
